{"name": "test_register_user_with_first_name_contains_special_characters", "status": "failed", "statusDetails": {"message": "AssertionError: Test Failed! Characters: '!, #, $, %, &, *, /, @, ?, ^, ', :, <, >, ~, {, }, _, +, -, =, |, [, ], (, ), ;, \\, \", `, ,' are not allowed", "trace": "self = <test_cases.test_001_registration_ddt.TestUserRegistration object at 0x00000254CF6D9810>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"4c64312faecb773958d805b3d75a6e27\")>\n\n    def test_register_user_with_first_name_contains_special_characters(self, setup):\n        self.open_register_form(setup)\n        self.logger.info(\"Starting test with first name contains special char\")\n        self.register_page = AccountRegistrationPage(setup)\n        f_name_with_char = [self.username + str(char) for char in self.chars]\n        not_allowed_chars = []\n        for f_name in f_name_with_char:\n            self.username = generate_random_username(7)\n            self.register_page.register(\n                self.username,\n                self.email,\n                self.password,\n                self.conf_password,\n                f_name,\n                self.last_name\n            )\n    \n            try:\n                expected_error_text = \"The name must contains only letters\"\n                error_text = self.register_page.get_error_message()\n                assert error_text.is_displayed()\n                assert error_text.text == expected_error_text\n            except NoSuchElementException:\n                not_allowed_chars.append(f_name[-1])\n                self.my_account_page = MyAccountPage(self.driver)\n                self.my_account_page.click_logout()\n            self.home_page = HomePage(self.driver)\n            self.home_page.click_register()\n    \n        if len(not_allowed_chars) > 0:\n>           raise AssertionError(f\"Test Failed! Characters: '{', '.join(not_allowed_chars)}' are not allowed\")\nE           AssertionError: Test Failed! Characters: '!, #, $, %, &, *, /, @, ?, ^, ', :, <, >, ~, {, }, _, +, -, =, |, [, ], (, ), ;, \\, \", `, ,' are not allowed\n\ntest_cases\\test_001_registration_ddt.py:598: AssertionError"}, "attachments": [{"name": "log", "source": "300a2d60-0c0b-4801-92a6-17da0b719697-attachment.txt", "type": "text/plain"}], "start": 1702721359704, "stop": 1702721450319, "uuid": "34ae37c6-76d4-4856-bdcf-a26c48b90548", "historyId": "a15a8c26c45566719787e8fbca000508", "testCaseId": "a15a8c26c45566719787e8fbca000508", "fullName": "test_001_registration_ddt.TestUserRegistration#test_register_user_with_first_name_contains_special_characters", "labels": [{"name": "suite", "value": "test_001_registration_ddt"}, {"name": "subSuite", "value": "TestUserRegistration"}, {"name": "host", "value": "DESKTOP-53FL5C3"}, {"name": "thread", "value": "13048-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_001_registration_ddt"}]}